"""Render the Dataform files for one gold table, deterministically, from the decisions.

Layout (paths come from the team's folder conventions):
  definitions/sources/<source>.sqlx           declaration, so ref() can reach the raw table
  includes/params/source_table/<source>.js    source parameters (projected columns)
  includes/params/target_table/<target>.js    target contract (types, keys, lineage)
  definitions/gold/<target>/<target>_read.sqlx     view: projection of the source
  definitions/gold/<target>/<target>_process.sqlx  view: one STTM rule per column
  definitions/gold/<target>/<target>_write.sqlx    table: casts to the contract + assertions

read/process are views, so BigQuery inlines them into the single query that
builds the table: no intermediate storage, no extra scans.
"""
import json
from dataclasses import dataclass, field

from app.inputs.repo import RepoConventions
from app.inputs.schema import TableSchema
from app.inputs.types import bigquery_type
from app.mapping.planner import default_sql
from app.warehouse.dialect import quote_ident

GENERATED_BY = "Generated by Mapfl0w"


@dataclass
class RenderInput:
    conventions: RepoConventions
    source: TableSchema
    target: TableSchema
    decisions: list[dict]
    read_columns: list[str]
    functions_name: str = "functions"        # identifier the SQLX uses for the UDF library
    functions_require: str | None = None     # set when functions.js is not a top-level include
    env_name: str | None = None              # global name of env_vars.js, if uploaded and top-level
    env_values: dict = field(default_factory=dict)


def udf_template(functions_name: str, name: str, args: list[str]) -> str:
    return "${" + f"{functions_name}.{name}(" + ", ".join(json.dumps(a) for a in args) + ")}"


def column_template(d: dict, functions_name: str) -> str:
    """The SQLX expression for one decision, before any default is applied."""
    if d.get("udf"):
        return udf_template(functions_name, d["udf"]["name"], d["udf"]["args"])
    return (d.get("sql") or "").strip()


def column_expression(d: dict, functions_name: str) -> str:
    """Full process-step expression: the rule, wrapped in COALESCE when the STTM gives a default."""
    expr = column_template(d, functions_name)
    dflt = default_sql(d.get("default", ""), d["target_type"])
    if dflt is not None and expr.strip() != dflt:
        expr = f"COALESCE({expr}, {dflt})"
    return expr


def _env_ref(env_name: str | None, env_values: dict, dataset: str) -> str:
    """Use the team's env var for a dataset name when one holds exactly that value, so the
    same code deploys to dev and prod; otherwise the literal name."""
    if not env_name:
        return json.dumps(dataset)
    matches = [k for k, v in env_values.items() if v == dataset]
    preferred = [k for k in matches if "dataset" in k.lower() or "schema" in k.lower()]
    key = (preferred or matches or [None])[0]
    return f"{env_name}.{key}" if key and key.isidentifier() else json.dumps(dataset)


class RawJs:
    """A config value emitted as JavaScript source (e.g. env_vars.gold_dataset), not as JSON."""

    def __init__(self, src: str):
        self.src = src


def js_literal(value, level: int = 0) -> str:
    """Python value -> idiomatic JS source: unquoted identifier keys, short lists inline."""
    pad = "  " * level
    if isinstance(value, RawJs):
        return value.src
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = []
        for k, v in value.items():
            key = k if k.isidentifier() else json.dumps(k)
            items.append(f"{pad}  {key}: {js_literal(v, level + 1)}")
        return "{\n" + ",\n".join(items) + f"\n{pad}}}"
    if isinstance(value, list):
        inline = "[" + ", ".join(js_literal(v, level + 1) for v in value) + "]"
        if len(inline) <= 72 and not any(isinstance(v, (dict, list)) for v in value):
            return inline
        return "[\n" + ",\n".join(f"{pad}  {js_literal(v, level + 1)}" for v in value) + f"\n{pad}]"
    return json.dumps(value, ensure_ascii=False)


def _config(entries: list[tuple[str, object]]) -> str:
    return "config " + js_literal(dict(entries))


def action_names(conv: RepoConventions, target: TableSchema) -> dict[str, str]:
    """Dataform action names must be unique project-wide, so steps are prefixed with the table name."""
    names = {step: conv.step_files[step].format(table=target.name).rsplit(".", 1)[0]
             for step in ("read", "process")}
    names["write"] = target.name  # the write step's action is the gold table itself
    return names


def _indent_continuation(expr: str, pad: str = "  ") -> str:
    return expr.replace("\n", "\n" + pad)


def provenance(d: dict) -> str:
    """Who decided this column, for the traceability comment: 'llm → udf fullName (cached)'."""
    label = {"reviewer": "reviewer override"}.get(d["method"], d["method"])
    if d.get("repaired"):
        label += " repaired by llm"
    udfs = d.get("udfs_used") or ([d["udf"]["name"]] if d.get("udf") else [])
    if udfs:
        names = ", ".join(udfs)
        label = f"udf {names}" if d["method"] == "udf" else f"{label} → udf {names}"
    return label + (" (cached)" if d.get("origin") == "cache" else "")


def render_files(inp: RenderInput) -> list[dict]:
    conv, src, tgt = inp.conventions, inp.source, inp.target
    table = tgt.name
    tags = ["gold", table]
    gold_schema = RawJs(_env_ref(inp.env_name, inp.env_values, tgt.dataset))
    names = action_names(conv, tgt)
    files: list[dict] = []

    # 1. source declaration (unless the repo already declares it)
    if not conv.existing_declaration(src.name):
        files.append({
            "path": conv.declaration_path(src.name), "kind": "declaration",
            "description": "Declares the raw source table so the pipeline can ref() it.",
            "content": _config([
                ("type", "declaration"),
                ("schema", RawJs(_env_ref(inp.env_name, inp.env_values, src.dataset))),
                ("name", src.name),
                ("description", f"Raw {src.name} ({GENERATED_BY} from source_schema.md)"),
            ]) + "\n",
        })

    # 2. params: source (what to read) and target (the contract)
    files.append({
        "path": conv.source_params_path(src.name), "kind": "source_params",
        "description": "Source-table parameters: only the columns the validated STTM rows use.",
        "content": (
            f"// {GENERATED_BY} from source_schema.md and the validated STTM rows.\n"
            f"// Only the columns the mappings use are listed: BigQuery bills per column scanned.\n"
            "module.exports = " + js_literal({
                "schema": src.dataset, "table": src.name, "columns": inp.read_columns,
            }) + ";\n"),
    })
    lineage = {}
    for d in inp.decisions:
        cols = d.get("read_columns") or ([d["source_field"]] if d["source_field"] else [])
        lineage[d["target_field"]] = {"sttm_row": d["row"], "source": cols, "method": d["method"]}
    files.append({
        "path": conv.target_params_path(tgt.name), "kind": "target_params",
        "description": "Target contract (types, keys, required columns) and column lineage.",
        "content": (
            f"// {GENERATED_BY} from target_schema.md: the contract the write step enforces.\n"
            "module.exports = " + js_literal({
                "schema": tgt.dataset, "table": tgt.name,
                "columns": {c.name: bigquery_type(c.type) for c in tgt.columns.values()},
                "uniqueKey": tgt.keys, "nonNull": tgt.required, "lineage": lineage,
            }) + ";\n"),
    })

    # 3. read step
    src_params = conv.module_path(conv.source_params_path(src.name))
    files.append({
        "path": conv.step_path("read", table), "kind": "read",
        "description": "Read step (view): projects the source columns the STTM uses.",
        "content": _config([
            ("type", "view"), ("schema", gold_schema), ("name", names["read"]), ("tags", tags),
            ("description", f"Read step: {len(inp.read_columns)} of {len(src.columns)} source columns "
                            "(projection keeps the BigQuery scan small)."),
        ]) + "\n\njs {\n  const source = require(" + json.dumps(src_params) + ");\n}\n\n"
             "SELECT\n  ${source.columns.join(\",\\n  \")}\nFROM ${ref(source.table)}\n",
    })

    # 4. process step: one line per target column, each traced to its STTM row
    by_target = {d["target_field"]: d for d in inp.decisions}
    lines = []
    for col in tgt.columns.values():
        d = by_target.get(col.name)
        alias = quote_ident(col.name)
        if d is None:
            lines.append(f"  -- no STTM row maps {col.name}\n  CAST(NULL AS {bigquery_type(col.type)}) AS {alias}")
            continue
        header = f"  -- row {d['row']} · {provenance(d)} · {d['source_field'] or '—'} → {col.name}"
        if d["status"] == "failed":
            reason = (d.get("error") or "failed verification").replace("*/", "* /").splitlines()[0][:160]
            lines.append(f"{header}\n  CAST(NULL AS {bigquery_type(col.type)}) AS {alias}"
                         f"  /* MAPFLOW: needs a human — {reason} */")
        else:
            lines.append(f"{header}\n  {_indent_continuation(d['expression'])} AS {alias}")
    js_block = ""
    if inp.functions_require:
        js_block = ("\n\njs {\n  const " + inp.functions_name + " = require("
                    + json.dumps(inp.functions_require) + ");\n}")
    files.append({
        "path": conv.step_path("process", table), "kind": "process",
        "description": "Process step (view): applies the STTM business rules, preferring team UDFs.",
        "content": _config([
            ("type", "view"), ("schema", gold_schema), ("name", names["process"]), ("tags", tags),
            ("description", "Process step: STTM business rules, one expression per target column."),
        ]) + js_block + "\n\nSELECT\n" + ",\n".join(lines)
          + f"\nFROM ${{ref({json.dumps(names['read'])})}}\n",
    })

    # 5. write step: contract enforcement + Dataform assertions
    assertions = {}
    if tgt.keys:
        assertions["uniqueKey"] = tgt.keys
    if tgt.required:
        assertions["nonNull"] = tgt.required
    config = [("type", "table"), ("schema", gold_schema), ("name", names["write"]), ("tags", tags),
              ("description", f"Gold table {tgt.table}, built from {src.table}. {GENERATED_BY}.")]
    described = {c.name: c.description for c in tgt.columns.values() if c.description}
    if described:
        config.append(("columns", described))
    if assertions:
        config.append(("assertions", assertions))
    casts = ",\n".join(f"  CAST({quote_ident(c.name)} AS {bigquery_type(c.type)}) AS {quote_ident(c.name)}"
                       for c in tgt.columns.values())
    files.append({
        "path": conv.step_path("write", table), "kind": "write",
        "description": "Write step (table): casts to the target contract; Dataform assertions check it.",
        "content": _config(config) + f"\n\nSELECT\n{casts}\nFROM ${{ref({json.dumps(names['process'])})}}\n",
    })
    return files
