/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewRunRouteImport } from './routes/new-run'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs.$runId.index'
import { Route as RunsRunIdReviewRouteImport } from './routes/runs.$runId.review'
import { Route as RunsRunIdResultRouteImport } from './routes/runs.$runId.result'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRunRoute = NewRunRouteImport.update({
  id: '/new-run',
  path: '/new-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/runs/$runId/',
  path: '/runs/$runId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdReviewRoute = RunsRunIdReviewRouteImport.update({
  id: '/runs/$runId/review',
  path: '/runs/$runId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdResultRoute = RunsRunIdResultRouteImport.update({
  id: '/runs/$runId/result',
  path: '/runs/$runId/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/new-run': typeof NewRunRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/runs/$runId/result': typeof RunsRunIdResultRoute
  '/runs/$runId/review': typeof RunsRunIdReviewRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/new-run': typeof NewRunRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/runs/$runId/result': typeof RunsRunIdResultRoute
  '/runs/$runId/review': typeof RunsRunIdReviewRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/new-run': typeof NewRunRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/runs/$runId/result': typeof RunsRunIdResultRoute
  '/runs/$runId/review': typeof RunsRunIdReviewRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/new-run'
    | '/settings'
    | '/sitemap.xml'
    | '/runs/$runId/result'
    | '/runs/$runId/review'
    | '/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/new-run'
    | '/settings'
    | '/sitemap.xml'
    | '/runs/$runId/result'
    | '/runs/$runId/review'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/new-run'
    | '/settings'
    | '/sitemap.xml'
    | '/runs/$runId/result'
    | '/runs/$runId/review'
    | '/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  NewRunRoute: typeof NewRunRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RunsRunIdResultRoute: typeof RunsRunIdResultRoute
  RunsRunIdReviewRoute: typeof RunsRunIdReviewRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-run': {
      id: '/new-run'
      path: '/new-run'
      fullPath: '/new-run'
      preLoaderRoute: typeof NewRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/runs/$runId'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/review': {
      id: '/runs/$runId/review'
      path: '/runs/$runId/review'
      fullPath: '/runs/$runId/review'
      preLoaderRoute: typeof RunsRunIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/result': {
      id: '/runs/$runId/result'
      path: '/runs/$runId/result'
      fullPath: '/runs/$runId/result'
      preLoaderRoute: typeof RunsRunIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  NewRunRoute: NewRunRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RunsRunIdResultRoute: RunsRunIdResultRoute,
  RunsRunIdReviewRoute: RunsRunIdReviewRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
