import type { ActivityEntry, EntryKind, Finding, Run } from "./types";

const MIN = 60_000;
const HOUR = 3_600_000;
const DAY = 24 * HOUR;

export const SQLX_SAMPLE = `config {
  type: "incremental",
  schema: "analytics",
  name: "fct_clinical_patients",
  uniqueKey: ["patient_id"],
  bigquery: {
    partitionBy: "DATE(ingest_date)"
  },
  tags: ["marts", "clinical"]
}

js {
  const { scd1Load } = require("includes/udfs");
}

-- Generated by Mapfl0w from sttm_clinical.csv (20 of 23 rows)
-- Rows 3, 9, 17 excluded: status "In Progress"

SELECT
  CAST(src.patient_id AS STRING)                    AS patient_id,
  INITCAP(TRIM(src.first_name))                     AS first_name,
  INITCAP(TRIM(src.last_name))                      AS last_name,
  LOWER(src.email_address)                          AS email_address,
  PARSE_DATE('%Y-%m-%d', src.dob_raw)               AS date_of_birth,
  CAST(src.weight_kg AS INT64)                      AS weight,        -- Row 12: lossy FLOAT -> INT
  ROUND(src.height_cm / 2.54, 1)                    AS height_in,     -- Row 8: translated from Python
  CASE
    WHEN src.gender_code = 'M' THEN 'Male'
    WHEN src.gender_code = 'F' THEN 'Female'
    ELSE 'Unknown'
  END                                               AS gender,
  COALESCE(src.primary_provider_id, 'UNASSIGNED')   AS provider_id,
  SAFE_CAST(src.risk_score AS NUMERIC)              AS risk_score,
  src.facility_code                                 AS facility_code,
  TIMESTAMP(src.admitted_at, 'UTC')                 AS admitted_at,
  CURRENT_TIMESTAMP()                               AS ingest_date
FROM \${ref("raw", "clinical_patients")} AS src
WHERE src.record_status = 'ACTIVE'
  \${when(incremental(), \`AND src.updated_at > (SELECT MAX(ingest_date) FROM \${self()})\`)}

post_operations {
  \${scd1Load(self(), "patient_id")}
}
`;

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "f1",
    severity: "warning",
    rows: "Row 12",
    message: "Lossy cast FLOAT → INT, defaulting to CAST(weight_kg AS INT)",
  },
  {
    id: "f2",
    severity: "info",
    rows: "Rows 3, 9, 17",
    message: "Status 'In Progress' — excluded from generation",
  },
  {
    id: "f3",
    severity: "info",
    rows: "Row 6",
    message: "Used scd1Load() per UDF definitions",
  },
  {
    id: "f4",
    severity: "warning",
    rows: "Row 8",
    message: "Translated Python snippet on row 8 to BigQuery SQL — verify",
  },
];

let entrySeq = 0;
function e(kind: EntryKind, text: string, ts: string): ActivityEntry {
  return { id: `me_${entrySeq++}`, kind, ts, text };
}

/** A complete historical feed for finished runs. */
export function completedFeed(table: string): ActivityEntry[] {
  return [
    e("thought", `Reading 4 input files — sttm sheet has 23 mapping rows`, "09:14:02"),
    e("tool_call", `parse_sttm(sttm_clinical.csv)`, "09:14:03"),
    e("tool_result", `23 rows parsed · 20 active · 3 status "In Progress"`, "09:14:04"),
    e("tool_call", `fetch_schema(raw.clinical_patients)`, "09:14:06"),
    e("tool_result", `31 columns · last modified 2026-07-10`, "09:14:07"),
    e("tool_call", `fetch_schema(${table})`, "09:14:08"),
    e("tool_result", `20 columns · partitioned by ingest_date`, "09:14:09"),
    e("thought", `Row 12 maps weight_kg (FLOAT) to weight (INT) with no cast — flagging lossy conversion`, "09:14:12"),
    e("tool_call", `generate_sqlx(${table.split(".")[1]})`, "09:14:15"),
    e("tool_result", `118 lines written · type: incremental · uses scd1Load()`, "09:14:24"),
    e("tool_call", `run_bq_dry_run(${table.split(".")[1]}.sqlx)`, "09:14:26"),
    e("tool_result", `dry run passed · 1.2 GB scanned · est. $0.006`, "09:14:31"),
    e("thought", `All checks green. Paused for human review`, "09:14:32"),
    e("tool_call", `github_push(kapil13007/dataform-models)`, "09:21:04"),
    e("tool_result", `commit 4f2a9c1 pushed · PR #87 opened`, "09:21:07"),
    e("tool_call", `dataform_execute(workspace: production)`, "09:21:10"),
    e("tool_result", `workflow wf_9d21 completed in 3m 41s`, "09:24:51"),
    e("tool_call", `audit_row_counts(${table})`, "09:24:53"),
    e("tool_result", `142,847 rows written · counts match · 0 nulls in required columns`, "09:24:58"),
    e("thought", `Run complete. Audit passed all 3 checks`, "09:24:59"),
  ];
}

function baseMeta(files = 4): Run["meta"] {
  const list = [
    "source_schema.md",
    "target_schema.md",
    "sttm_clinical.csv",
    "repo_structure.md",
    "udf_definitions.md",
  ];
  return { files: list.slice(0, files), llmAttempts: 2, approvedBy: "kapil", workflowId: "wf_9d21" };
}

const now = Date.now();

export const MOCK_RUNS: Run[] = [
  {
    id: "run_0042",
    targetTable: "analytics.fct_clinical_patients",
    status: "running",
    mappingsValidated: 20,
    mappingsExcluded: 3,
    costGb: null,
    costUsd: null,
    startedAt: now - 40_000,
    durationSec: null,
    currentStep: 0,
    feed: [],
    findings: [],
    sqlx: SQLX_SAMPLE,
    sqlxPath: "definitions/marts/fct_clinical_patients.sqlx",
    meta: { files: baseMeta(5).files, llmAttempts: 2 },
  },
  {
    id: "run_0041",
    targetTable: "analytics.fct_lab_results",
    status: "awaiting_review",
    mappingsValidated: 34,
    mappingsExcluded: 1,
    costGb: 2.8,
    costUsd: 0.014,
    startedAt: now - 35 * MIN,
    durationSec: null,
    currentStep: 4,
    feed: completedFeed("analytics.fct_lab_results").slice(0, 13),
    findings: MOCK_FINDINGS,
    sqlx: SQLX_SAMPLE.replaceAll("fct_clinical_patients", "fct_lab_results"),
    sqlxPath: "definitions/marts/fct_lab_results.sqlx",
    meta: { files: baseMeta(4).files.slice(0, 4), llmAttempts: 1 },
  },
  {
    id: "run_0040",
    targetTable: "analytics.dim_providers",
    status: "succeeded",
    mappingsValidated: 14,
    mappingsExcluded: 0,
    costGb: 0.4,
    costUsd: 0.002,
    startedAt: now - 3 * HOUR,
    durationSec: 512,
    currentStep: 7,
    feed: completedFeed("analytics.dim_providers"),
    findings: MOCK_FINDINGS.slice(2),
    sqlx: SQLX_SAMPLE.replaceAll("fct_clinical_patients", "dim_providers"),
    sqlxPath: "definitions/marts/dim_providers.sqlx",
    audit: { rowsWritten: 4_812, countsMatch: true, nullsCheck: true },
    meta: baseMeta(4),
  },
  {
    id: "run_0039",
    targetTable: "analytics.fct_appointments",
    status: "failed",
    mappingsValidated: 27,
    mappingsExcluded: 2,
    costGb: 3.1,
    costUsd: 0.016,
    startedAt: now - 8 * HOUR,
    durationSec: 947,
    currentStep: 7,
    stepFailed: true,
    feed: completedFeed("analytics.fct_appointments"),
    findings: MOCK_FINDINGS.slice(0, 2),
    sqlx: SQLX_SAMPLE.replaceAll("fct_clinical_patients", "fct_appointments"),
    sqlxPath: "definitions/marts/fct_appointments.sqlx",
    audit: {
      rowsWritten: 88_102,
      countsMatch: false,
      nullsCheck: true,
      failedCheck: "Row counts differ: source 88,214 vs target 88,102 (−112 rows)",
    },
    meta: baseMeta(4),
  },
  {
    id: "run_0038",
    targetTable: "analytics.dim_patients",
    status: "rejected",
    mappingsValidated: 18,
    mappingsExcluded: 4,
    costGb: 1.9,
    costUsd: 0.01,
    startedAt: now - DAY,
    durationSec: 610,
    currentStep: 4,
    feed: completedFeed("analytics.dim_patients").slice(0, 13),
    findings: MOCK_FINDINGS,
    sqlx: SQLX_SAMPLE.replaceAll("fct_clinical_patients", "dim_patients"),
    sqlxPath: "definitions/marts/dim_patients.sqlx",
    meta: { ...baseMeta(5), approvedBy: undefined, workflowId: undefined },
  },
  {
    id: "run_0037",
    targetTable: "analytics.fct_prescriptions",
    status: "succeeded",
    mappingsValidated: 22,
    mappingsExcluded: 1,
    costGb: 1.6,
    costUsd: 0.008,
    startedAt: now - 2 * DAY,
    durationSec: 688,
    currentStep: 7,
    feed: completedFeed("analytics.fct_prescriptions"),
    findings: MOCK_FINDINGS.slice(1, 3),
    sqlx: SQLX_SAMPLE.replaceAll("fct_clinical_patients", "fct_prescriptions"),
    sqlxPath: "definitions/marts/fct_prescriptions.sqlx",
    audit: { rowsWritten: 512_004, countsMatch: true, nullsCheck: true },
    meta: baseMeta(5),
  },
  {
    id: "run_0036",
    targetTable: "analytics.dim_facilities",
    status: "succeeded",
    mappingsValidated: 9,
    mappingsExcluded: 0,
    costGb: 0.1,
    costUsd: 0.001,
    startedAt: now - 3 * DAY,
    durationSec: 402,
    currentStep: 7,
    feed: completedFeed("analytics.dim_facilities"),
    findings: [],
    sqlx: SQLX_SAMPLE.replaceAll("fct_clinical_patients", "dim_facilities"),
    sqlxPath: "definitions/marts/dim_facilities.sqlx",
    audit: { rowsWritten: 143, countsMatch: true, nullsCheck: true },
    meta: baseMeta(4),
  },
  {
    id: "run_0035",
    targetTable: "analytics.fct_claims",
    status: "succeeded",
    mappingsValidated: 41,
    mappingsExcluded: 5,
    costGb: 6.4,
    costUsd: 0.032,
    startedAt: now - 5 * DAY,
    durationSec: 1_204,
    currentStep: 7,
    feed: completedFeed("analytics.fct_claims"),
    findings: MOCK_FINDINGS,
    sqlx: SQLX_SAMPLE.replaceAll("fct_clinical_patients", "fct_claims"),
    sqlxPath: "definitions/marts/fct_claims.sqlx",
    audit: { rowsWritten: 1_284_930, countsMatch: true, nullsCheck: true },
    meta: baseMeta(5),
  },
  {
    id: "run_0034",
    targetTable: "analytics.dim_medications",
    status: "failed",
    mappingsValidated: 12,
    mappingsExcluded: 0,
    costGb: 0.8,
    costUsd: 0.004,
    startedAt: now - 6 * DAY,
    durationSec: 355,
    currentStep: 3,
    stepFailed: true,
    feed: completedFeed("analytics.dim_medications").slice(0, 11),
    findings: MOCK_FINDINGS.slice(0, 1),
    sqlx: SQLX_SAMPLE.replaceAll("fct_clinical_patients", "dim_medications"),
    sqlxPath: "definitions/marts/dim_medications.sqlx",
    meta: { files: baseMeta(4).files.slice(0, 4), llmAttempts: 3 },
  },
];

/** Sample file contents shown in the New Run preview panel when a real file can't be read. */
export const FILE_PREVIEW_FALLBACK: Record<string, string> = {
  source: `# Source schema — raw.clinical_patients\n\n| column | type | notes |\n|---|---|---|\n| patient_id | INT64 | primary key |\n| first_name | STRING | |\n| last_name | STRING | |\n| email_address | STRING | |\n| dob_raw | STRING | YYYY-MM-DD |\n| weight_kg | FLOAT64 | |\n| height_cm | FLOAT64 | |\n| gender_code | STRING | M/F/NULL |\n| risk_score | STRING | numeric-ish |\n| admitted_at | DATETIME | source-local |\n`,
  target: `# Target schema — analytics.fct_clinical_patients\n\n| column | type | required |\n|---|---|---|\n| patient_id | STRING | yes |\n| first_name | STRING | yes |\n| email_address | STRING | yes |\n| date_of_birth | DATE | yes |\n| weight | INT64 | no |\n| height_in | FLOAT64 | no |\n| gender | STRING | yes |\n| risk_score | NUMERIC | no |\n| ingest_date | TIMESTAMP | yes |\n`,
  sttm: `row,source_column,transformation,target_column,status\n1,patient_id,CAST TO STRING,patient_id,Ready\n2,first_name,INITCAP + TRIM,first_name,Ready\n3,middle_name,,middle_name,In Progress\n4,last_name,INITCAP + TRIM,last_name,Ready\n5,email_address,LOWER,email_address,Ready\n6,record,scd1Load on patient_id,—,Ready\n7,email_address,LOWER,email_address,Ready\n8,height_cm,"python: round(x / 2.54, 1)",height_in,Ready\n9,ssn_hash,,ssn_hash,In Progress\n12,weight_kg,,weight,Ready\n`,
  repo: `# Repo structure — dataform-models\n\ndefinitions/\n  staging/    -- stg_ prefixed, one per source table\n  marts/      -- fct_ / dim_ prefixed\nincludes/\n  udfs.js     -- shared UDFs\n\nDefaults: type=incremental for fct_, table for dim_.\nPartition all fct_ tables on ingest_date.\n`,
  udf: `# UDF definitions\n\n## scd1Load(table, key)\nType-1 upsert into \\\`table\\\` on \\\`key\\\`. Use for all dim/fct loads.\n\n## factLoad(table, key, watermark)\nIncremental append with late-arriving-data window.\n\n## cleanString(col)\nTRIM + normalize whitespace + NULLIF('').\n`,
};